// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjSEytqMT-wRYNIMrtxd9MBS1KE36TVu0',
    appId: '1:775220676895:web:0bf13fdd60f96db6cfc82a',
    messagingSenderId: '775220676895',
    projectId: 'chat-app-2ea72',
    authDomain: 'chat-app-2ea72.firebaseapp.com',
    storageBucket: 'chat-app-2ea72.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEjRQzAklJKy3n8Dkvan19Gc-2OZLU2lM',
    appId: '1:775220676895:android:096466118f891d20cfc82a',
    messagingSenderId: '775220676895',
    projectId: 'chat-app-2ea72',
    storageBucket: 'chat-app-2ea72.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1z0-dyoDt3okdHDWmsvVQXK7C79pGeu4',
    appId: '1:775220676895:ios:e227aadd74f90b2ccfc82a',
    messagingSenderId: '775220676895',
    projectId: 'chat-app-2ea72',
    storageBucket: 'chat-app-2ea72.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1z0-dyoDt3okdHDWmsvVQXK7C79pGeu4',
    appId: '1:775220676895:ios:e227aadd74f90b2ccfc82a',
    messagingSenderId: '775220676895',
    projectId: 'chat-app-2ea72',
    storageBucket: 'chat-app-2ea72.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjSEytqMT-wRYNIMrtxd9MBS1KE36TVu0',
    appId: '1:775220676895:web:a951951c2fc388c2cfc82a',
    messagingSenderId: '775220676895',
    projectId: 'chat-app-2ea72',
    authDomain: 'chat-app-2ea72.firebaseapp.com',
    storageBucket: 'chat-app-2ea72.firebasestorage.app',
  );
}
